# Generated by Django 3.1.7 on 2021-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message_id',
            field=models.IntegerField(default=123, verbose_name='Message ID'),
        ),
    ]
