# Generated by Django 3.1.7 on 2021-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='message_id',
            field=models.IntegerField(unique=True, verbose_name='Message ID'),
        ),
    ]
