# Generated by Django 3.1.7 on 2021-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210327_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teluser',
            name='tel_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telegram Username'),
        ),
    ]
