# Generated by Django 3.1.7 on 2021-04-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210328_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=300)),
                ('qid', models.IntegerField(unique=True)),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teluser')),
            ],
        ),
    ]
