# Generated by Django 3.1.7 on 2021-04-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_detailedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedquestion',
            name='answer',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='detailedquestion',
            name='date_answered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teluser'),
        ),
    ]
