# Generated by Django 3.1.7 on 2021-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210416_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedquestion',
            name='date_answered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
