# Generated by Django 3.1.7 on 2021-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210417_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
