# Generated by Django 3.1.7 on 2021-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210430_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
    ]
